Repository CS-SI/eodag, pull requests merged in 2024-09, with the labels that each got.

#1257 fix(plugins): raise error if no data available on AwsDownload
  eodag/plugins/download/aws.py
  tests/units/test_download_plugins.py
Labels: bug, dedl

#1278 fix(server): correct STAC collection generation
  eodag/resources/stac.yml
  eodag/rest/stac.py
Labels: dedl

#1284 refactor(provider): new cds api
  docs/getting_started_guide/register.rst
  docs/notebooks/tutos/tuto_cds.ipynb
  eodag/api/product/metadata_mapping.py
  eodag/resources/providers.yml
  eodag/resources/user_conf_template.yml
  tests/units/test_core.py
  tests/units/test_download_plugins.py
  tests/units/test_http_server.py
  tests/units/test_search_plugins.py
Labels: dedl

#1304 fix(plugins): build_search_result end_date preprocessing
  eodag/plugins/search/build_search_result.py
  tests/units/test_search_plugins.py
Labels: dedl

#1313 fix(providers): usage of `hydrological_year` in provider `wekeo_ecmwf`
  eodag/api/core.py
  eodag/api/product/metadata_mapping.py
  eodag/resources/providers.yml
  tests/units/test_search_plugins.py
Labels: dedl

#1323 fix(server): send search_stac_items in its own threadpool
  eodag/rest/server.py
Labels: bug, dedl

#1318 fix(server): queryable issues and parameters prefixes
  eodag/resources/providers.yml
  eodag/rest/core.py
  eodag/rest/types/eodag_search.py
  tests/units/test_http_server.py
Labels: dedl

#1301 fix(providers): handle cop_marine in situ historical data
  eodag/plugins/search/cop_marine.py
  eodag/resources/product_types.yml
  eodag/resources/providers.yml
  tests/units/test_search_plugins.py
Labels: dedl

#1237 feat(core): improve search and authentication errors format
  eodag/api/core.py
  eodag/api/search_result.py
  eodag/plugins/apis/usgs.py
  eodag/plugins/authentication/generic.py
  eodag/plugins/authentication/openid_connect.py
  eodag/plugins/authentication/qsauth.py
  eodag/plugins/authentication/sas_auth.py
  eodag/plugins/authentication/token.py
  eodag/plugins/download/aws.py
  eodag/plugins/download/http.py
  eodag/plugins/download/s3rest.py
  eodag/plugins/search/build_search_result.py
  eodag/plugins/search/creodias_s3.py
  eodag/plugins/search/data_request_search.py
  eodag/plugins/search/qssearch.py
  eodag/rest/core.py
  eodag/rest/errors.py
  eodag/rest/server.py
  eodag/rest/types/eodag_search.py
  eodag/utils/exceptions.py
  eodag/utils/requests.py
  tests/context.py
  tests/units/test_auth_plugins.py
  tests/units/test_http_server.py
  tests/units/test_search_plugins.py
Labels: server, dedl

#1306 fix(server): remove catalogs
  README.rst
  docs/_static/stac_browser_example.png
  docs/_static/stac_browser_example_600.png
  docs/stac_rest.rst
  eodag/resources/stac.yml
  eodag/rest/constants.py
  eodag/rest/core.py
  eodag/rest/server.py
  eodag/rest/stac.py
  tests/units/test_http_server.py
  tests/units/test_stac_core.py
Labels: dedl
