Repository CS-SI/eodag, pull requests merged in 2024-11, with the labels that each got.

#1370 fix(plugins): auth only when needed during http download
  eodag/plugins/download/http.py
  tests/units/test_download_plugins.py
Labels: dedl

#1390 fix(plugins): Validation error if 400 error during order
  eodag/plugins/download/http.py
  eodag/utils/__init__.py
  eodag/utils/exceptions.py
  tests/units/test_download_plugins.py
Labels: dedl

#1392 fix(providers): FIRE_HISTORICAL on wekeo_ecmwf
  eodag/resources/product_types.yml
  eodag/resources/providers.yml
  tests/units/test_core.py
Labels: dedl

#1353 feat(server): add dedicated liveness endpoint
  charts/eodag-server/templates/deployment.yaml
  eodag/cli.py
  eodag/rest/server.py
  eodag/rest/utils/__init__.py
  tests/units/test_http_server.py
Labels: server, dedl

#1418 fix(openid_connect): compare only offset-aware datetimes
  eodag/plugins/authentication/openid_connect.py
Labels: bug
