Repository CS-SI/eodag, pull requests merged in 2025-01, with the labels that each got.

#1425 fix(plugins): creodias_s3 search and download when no asset
  eodag/plugins/download/aws.py
  eodag/plugins/download/creodias_s3.py
  eodag/plugins/search/creodias_s3.py
  tests/units/test_download_plugins.py
  tests/units/test_search_plugins.py
Labels: bug, dedl

#1400 fix(plugins): remove default HTTPDownload zip extension
  docs/notebooks/tutos/tuto_cds.ipynb
  docs/notebooks/tutos/tuto_ecmwf.ipynb
  eodag/api/product/_product.py
  eodag/plugins/download/base.py
  eodag/plugins/download/http.py
  eodag/resources/providers.yml
  eodag/types/download_args.py
  tests/__init__.py
  tests/units/test_download_plugins.py
  tests/units/test_eoproduct.py
Labels: dedl

#1427 fix(wekeo-ecmwf): correct queryables
  eodag/api/product/metadata_mapping.py
  eodag/plugins/search/build_search_result.py
  eodag/resources/providers.yml
  tests/units/test_search_plugins.py
Labels: bug, dedl

#1472 fix(server): add default datetime in dedt_lumi generated items
  eodag/resources/providers.yml
  eodag/rest/stac.py
Labels: bug, dedl

#1471 fix(cop_marine): search_by_id for products without date in id
  eodag/plugins/search/cop_marine.py
  tests/units/test_search_plugins.py
Labels: bug, dedl

#1431 feat(core): merge queryables by provider priority
  eodag/api/core.py
  eodag/plugins/search/base.py
  eodag/plugins/search/build_search_result.py
  eodag/types/queryables.py
  tests/units/test_core.py
Labels: bug, dedl

#1480 fix: metadata mapping for date parameter
  eodag/api/product/metadata_mapping.py
Labels: bug, server

#1475 fix(plugins): raise error on failed empty stream_zip
  eodag/plugins/download/http.py
  tests/units/test_download_plugins.py
Labels: bug, dedl

#1436 docs: update tutorials using eodag-cube
  docs/notebooks/api_user_guide/1_overview.ipynb
  docs/notebooks/api_user_guide/4_search.ipynb
  docs/notebooks/api_user_guide/9_post_process.ipynb
  docs/notebooks/tutos/tuto_cds.ipynb
  docs/notebooks/tutos/tuto_ecmwf.ipynb
  docs/notebooks/tutos/tuto_meteoblue.ipynb
  eodag/resources/providers.yml
  setup.cfg
  tests/units/test_apis_plugins.py
Labels: dedl
